Repository nnine-tech/nnine-training, pull requests merged in 2024-12, with the labels that each got.

#184 fix: bug
  backend/Controller/authenticationController.js
  backend/Controller/courseController.js
  backend/Controller/courseSyllabusController.js
  backend/Model/coursesyllabusModel.js
  backend/Routes/adminRoute.js
  backend/app.js
Labels: bug

#185 feat: admin dashboard
  backend/Controller/courseController.js
  backend/Controller/errorController.js
  backend/Controller/feesController.js
  backend/Controller/n9reviewController.js
  backend/Controller/sendFileController.js
  backend/Controller/studentController.js
  backend/Model/notificationModel.js
  backend/Model/studentModel.js
  backend/Routes/feesRoute.js
  backend/Routes/studentRoute.js
  backend/app.js
  backend/config.env
  backend/package-lock.json
  backend/package.json
  backend/utils/sendFile.js
  text.txt
Labels: backend

#187 feat: Khalti Payment Integration
  backend/.env.example
  backend/Controller/khaltiController.js
  backend/Controller/khaltiPaymentController.js
  backend/Model/paymentModel.js
  backend/Model/productModel.js
  backend/Model/purchasedProductModel.js
  backend/Routes/completeKhaltiPayment.js
  backend/Routes/khaltiPaymentRoute.js
  backend/Utils/sendMail.js
  backend/app.js
  backend/config.env
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: backend

#193 feat: google oauth updated
  backend/Controller/authenticationController.js
  backend/Controller/khaltiController.js
  backend/Controller/khaltiPaymentController.js
  backend/Controller/passportController.js
  backend/Controller/verificationController.js
  backend/Model/newAdminModel.js
  backend/Routes/adminRoute.js
  backend/Routes/khaltiPaymentRoute.js
  backend/Routes/passportRoute.js
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/services/passportConfig.js
Labels: backend

#218 217 about us responsive
  package-lock.json
  package.json
  src/components/About.js
  src/components/Navbar2.js
  tailwind.config.js
  yarn.lock
Labels: enhancement, frontend

#220 219 about us change
  src/components/About.js
  tailwind.config.js
Labels: enhancement, frontend

#222 feat: course-width-change
  src/components/Footer.js
  src/components/UIUXClassType.js
  src/components/UIUXSyllabus1.js
Labels: enhancement, frontend

#224 feat: footer-and-course
  src/components/UIUXClassType.js
  src/components/UIUXSyllabus1.js
Labels: enhancement, frontend

#226 feat: about-responsive-large
  src/components/About.js
Labels: enhancement, frontend

#227 feat: db connection setup
  attendance-be/.dockerignore
  attendance-be/.gitignore
  attendance-be/Dockerfile
  attendance-be/README
  attendance-be/config/config.json
  attendance-be/config/database.js
  attendance-be/models/index.js
  attendance-be/package-lock.json
  attendance-be/package.json
  attendance-be/src/app.js
  attendance-be/src/index.js
Labels: backend

#230 feat: new-syllabus-added
  public/SPSS.jpg
  public/markdown/courselist.md
  src/Syllabus/SPSS.js
  src/app/Syllabus/SPSS/page.js
  src/components/Footer.js
  src/components/Navbar.js
  src/components/Navbar2.js
  src/components/SPSSClassType.js
  src/components/SPSSintro.js
  src/components/SPSSsyllabus.js
Labels: enhancement, frontend

#231 feat: department
  attendance-be/README
  attendance-be/models/department.model.js
  attendance-be/models/index.js
  attendance-be/package-lock.json
  attendance-be/package.json
  attendance-be/src/app.js
  attendance-be/src/controllers/department.controller.js
  attendance-be/src/middlewares/apiError.js
  attendance-be/src/routes/department.router.js
  attendance-be/src/services/department.service.js
  attendance-be/src/utils/ApiError.js
  attendance-be/src/utils/ApiResponse.js
  attendance-be/src/utils/asyncHandler.js
  attendance-be/src/validators/department.validate.js
Labels: backend

#233 feat: user auth and attendance
  attendance-be/models/attendance.model.js
  attendance-be/models/role.model.js
  attendance-be/models/user.model.js
  attendance-be/package-lock.json
  attendance-be/package.json
  attendance-be/src/app.js
  attendance-be/src/controllers/attendance.controller.js
  attendance-be/src/controllers/auth.controller.js
  attendance-be/src/controllers/role.controller.js
  attendance-be/src/controllers/user.controller.js
  attendance-be/src/middlewares/authAllRoles.js
  attendance-be/src/middlewares/authManagerOnly.js
  attendance-be/src/routes/attendance.rotuer.js
  attendance-be/src/routes/auth.router.js
  attendance-be/src/routes/role.router.js
  attendance-be/src/routes/user.router.js
  attendance-be/src/services/attendance.service.js
  attendance-be/src/services/password.service.js
  attendance-be/src/services/role.service.js
  attendance-be/src/services/token.service.js
  attendance-be/src/services/user.service.js
  attendance-be/src/validators/role.validate.js
  attendance-be/src/validators/user.validate.js
Labels: backend

#236 feat: attendace enhance
  attendance-be/models/associations.js
  attendance-be/models/attendance.model.js
  attendance-be/models/holiday.model.js
  attendance-be/models/user.model.js
  attendance-be/models/workschedule.model.js
  attendance-be/package-lock.json
  attendance-be/package.json
  attendance-be/src/app.js
  attendance-be/src/controllers/attendance.controller.js
  attendance-be/src/controllers/auth.controller.js
  attendance-be/src/controllers/holiday.controller.js
  attendance-be/src/controllers/user.controller.js
  attendance-be/src/controllers/workSchedule.controller.js
  attendance-be/src/cron/attendance.job.js
  attendance-be/src/index.js
  attendance-be/src/routes/holiday.router.js
  attendance-be/src/routes/user.router.js
  attendance-be/src/routes/workSchedule.rouer.js
  attendance-be/src/services/attendance.service.js
  attendance-be/src/services/holiday.service.js
  attendance-be/src/services/token.service.js
  attendance-be/src/services/user.service.js
  attendance-be/src/services/workSchedule.service.js
  attendance-be/src/validators/user.validate.js
Labels: enhancement, backend

#237 feat: leave request
  attendance-be/models/leaveRequest.model.js
  attendance-be/models/user.model.js
  attendance-be/src/app.js
  attendance-be/src/controllers/attendance.controller.js
  attendance-be/src/controllers/leaveRequest.controller.js
  attendance-be/src/controllers/user.controller.js
  attendance-be/src/middlewares/authManagerOnly.js
  attendance-be/src/routes/leaveRequest.router.js
  attendance-be/src/services/attendance.service.js
  attendance-be/src/services/leaveRequest.service.js
  attendance-be/src/services/user.service.js
  attendance-be/src/validators/leaveRequest.validate.js
  attendance-be/src/validators/user.validate.js
Labels: backend

#240 fix: footer later spacing
  src/components/Footer.js
  yarn.lock
Labels: enhancement, frontend

#241 feat: navbar changes
  src/app/layout.js
  src/components/Navbar.js
  src/components/SPSSintro.js
Labels: enhancement, frontend
