Repository nnine-tech/nnine-training, pull requests merged in 2025-01, with the labels that each got.

#244 feat: for-search-optimization
  package-lock.json
  src/app/layout.js
  src/app/page.js
  yarn.lock
Labels: seo

#247 feat: devops-markdown-syllabus
  public/markdown/syllabus/devops.md
  src/components/DevopsSyllabus1.js
Labels: frontend

#249 feat: markdown file added
  package-lock.json
  package.json
  public/markdown/syllabus/devops.md
  public/markdown/syllabus/flutter.md
  src/components/ClassType.js
  src/components/DevopsClassType.js
  src/components/DevopsSyllabus1.js
  src/components/FlutterClassType.js
  src/components/FlutterSyllabus1.js
  yarn.lock
Labels: enhancement, frontend

#250 feat: seo-pagewithredirect
  package-lock.json
  package.json
  public/markdown/blogs/blogs.md
  public/markdown/syllabus/devops.md
  src/components/DevopsSyllabus1.js
  src/components/Footer.js
  src/components/Hero2.js
  src/components/Navbar.js
  yarn.lock
Labels: seo

#252 feat: mern-markdown-edit
  public/markdown/syllabus/mernstack.md
  src/components/CourseSyllabus1.js
Labels: enhancement, frontend

#254 feat: uiux-markdown-added
  public/markdown/syllabus/uiux.md
  src/components/CourseSyllabus1.js
  src/components/UIUXSyllabus1.js
Labels: enhancement, frontend

#256 feat: python-markdown-added
  public/markdown/syllabus/python.md
  public/markdown/syllabus/uiux.md
  src/components/PythonSyllabus1.js
Labels: enhancement, frontend

#258 feat: webdev-markdown-added
  public/markdown/syllabus/python.md
  public/markdown/syllabus/webdevelopment.md
  src/components/CourseSyllabus1.js
  src/components/PythonSyllabus1.js
  src/components/UIUXSyllabus1.js
  src/components/WebdevelopmentSyllabus1.js
Labels: enhancement, frontend

#260 feat: data-ml-markdown-added
  public/markdown/syllabus/datascienceandml.md
  src/components/DataScienceAndMLSyllabus1.js
Labels: enhancement, frontend

#263 feat: syllabus markdown added
  public/markdown/syllabus/QA.md
  public/markdown/syllabus/awsdevelopment.md
  public/markdown/syllabus/awssolution.md
  public/markdown/syllabus/basiccomputer.md
  public/markdown/syllabus/cplus.md
  public/markdown/syllabus/openshift.md
  public/markdown/syllabus/redhatadministrator.md
  public/markdown/syllabus/redhatopenshift.md
  public/markdown/syllabus/spss.md
  src/components/AWSDevelopmentClassType.js
  src/components/AWSDevelopmentSyllabus1.js
  src/components/AWSSolutionClassType.js
  src/components/AWSSolutionSyllabus1.js
  src/components/BasicComputerClassType.js
  src/components/BasicComputerSyllabus1.js
  src/components/CPlusSyllabus1.js
  src/components/Footer.js
  src/components/Navbar.js
  src/components/OpenShiftClassType.js
  src/components/OpenShiftSyllabus1.js
  src/components/QAClassType.js
  src/components/QASyllabus1.js
  src/components/RedHatAdministratorSyllabus1.js
  src/components/RedHatOpenShiftSyllabus1.js
  src/components/SPSSsyllabus.js
Labels: enhancement, frontend

#265 feat: blog-navigation-solved
  src/components/Footer.js
  src/components/Navbar.js
Labels: enhancement, frontend
